stages:
  - format

format_json:
  stage: format
  image: alpine:latest
  before_script:
    - apk add --no-cache jq git
    - git remote remove origin
    - git remote add origin https://oauth2:$OAUTH_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
  script:
    - echo "Current branch:" $CI_COMMIT_REF_NAME
    - for file in Notebooks/*.ipynb; do jq --indent 1 . "$file" > tmp && mv tmp "$file"; done
    - git config --global user.email "ci-bot@example.com"
    - git config --global user.name "CI Bot"
    - git fetch --unshallow
    - git add --all
    - git commit -m "Formatted IPYNB files"
    - git push origin HEAD:main
  rules:
    - changes:
        - "*.ipynb"