minimum = ...
maximum = ...

while ... :
    
    proposition = ...
    print("Ma proposition est", proposition)
    
    reponse = input("Plus grand ou plus petit (g ou p) : ")
    if reponse == 'g':
        ...
    elif ... :
        ...

